### ISSUE TITLE
Help creating a Ichimoku Cloud Strategy bot

### ISSUE THREAD

**Issue by Kanjowuu** [binary-ex-machina/binary.com-bot#53]
Pls help me create a bot with the ichimoku cloud strategy like this

For Strong Signals: Tenkan Sen/Kijun Sen (duration maybe 2-5 mins)
– BUY when Tenkan Sen cross Kijun Sen with direction up, and ABOVE Kumo cloud
– SELL when Tenkan Sen cross Kijun Sen with direction down, and UNDER Kumo cloud

For Medium Signals: Tenkan Sen/Kijun Sen (duration maybe 1 min)
– BUY when Tenkan Sen cross Kijun Sen with direction up, and INSIDE Kumo cloud
– SELL when Tenkan Sen cross Kijun Sen with direction down, and INSIDE Kumo cloud

For Week Signals: Tenkan Sen/Kijun Sen (duration maybe 1 min)
– BUY when Tenkan Sen cross Kijun Sen with direction up, and UNDER Kumo cloud
– SELL when Tenkan Sen cross Kijun Sen with direction down, and ABOVE Kumo cloud

This is the main part of it, maybe if possible then add one more thing is the Chikou Span. If we got a buy signal, and chikou span is ABOVE the present price, then the signal will be stronger. If we got a sell signal, and chikou span is UNDER the present price, the the signal will be stronger.

Pls help me with this, i will pay the fee if needed, because this strategy work almost all the time when i do manual trade.

**Comment by binary-ex-machina** [comment]
this will have some complex ideas on it, but it will be very hard to have all this in one bot. I think you need to spread each type of signal into a bot. I have created the Ichimoku Cloud indicator some time ago and you can find it [here](https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#ichimoku-cloud)

Below the filter of the Strong Signals part

![image](https://user-images.githubusercontent.com/34610787/46262245-01148400-c4d5-11e8-8876-499488796c42.png)

As you can see the first block cloudBefore have all the elements of the indicator in a form of list (i'm using "All" on the input of the ::signal

![image](https://user-images.githubusercontent.com/34610787/46262270-446ef280-c4d5-11e8-8ca0-1bfcfdf2d58f.png)

This will return a list with 5 items from the past candle.

then i store the last value of the cloud, on the variable Cloud, with the same settings from the cloudBefore.

After that i make the cross check
![image](https://user-images.githubusercontent.com/34610787/46262287-88fa8e00-c4d5-11e8-9542-c2277c103600.png)

Since cloudBefore is a list, i need to get the first element (Tenkan) and compare with the second element (Kijun). First element must be below. Then i make another comparison, checking if the actual cloud first element (Tenkan) is above the second element (Kijun). This way i have the crossover validation between two signals.

Next i do the check if the first element of the actual cloud (Tenkan) is above the Kumo cloud (Span A and B formation). Span A is the 4th element in the cloud list, Span B is the 5th.

![image](https://user-images.githubusercontent.com/34610787/46262310-eabaf800-c4d5-11e8-9ed3-48b26b6fb29c.png)

this way i get the Rise condition on your strategy.

The Fall trade type is exactly the opposite

![image](https://user-images.githubusercontent.com/34610787/46262316-045c3f80-c4d6-11e8-9858-014e1c75b6ed.png)

to be sure that the Tenkan is inside de Kumo cloud, the value of the Tenkan needs to be between both. In this case you need to see what Span is above and then check if the Tenkan is inside

![image](https://user-images.githubusercontent.com/34610787/46262381-aa0fae80-c4d6-11e8-9097-c84ea6724d7f.png)

if 4th in cloud (Span A) is above 5th in cloud (Span B), it means the Kumo is green (uptrend). If the 4th is below, is downtrend. With this you compare the 1st in cloud (Tenkan). With this you get if it's inside or not.

I checked the charts and the strategy generates a lot of false signals. Ichimoku cloud is a very nice indicator, but i don't think it will work with trades with expiration date (like binary options)

**Comment by Kanjowuu** [comment]
Thank you for your effort thiago, pls reply me on Facebook too, i was contacting you for an offer xD
