### ISSUE TITLE
Source of Volatility Index - Binary.com

### ISSUE THREAD

**Issue by duyorion** [binary-ex-machina/binary.com-bot#67]
Hello everyone,

I am wondering if binary.com uses which source to generate their Volatility 10, 25, etc,... index charts? We need to compare if they are manipulating their own markets.

I see that the VIX CBOE is around 13.xxxx but in binary.com it is 2.xxx.

Thank you!

**Comment by binary-ex-machina** [comment]
volatility indexes are synthetic markets, generated by code based on real markets. If you think they manipulate the markets, use other platform. It's very hard to find brokers that have the same graph, identical ticks. Since they subscribe to receive the ticks from a source (forex markets, commodities and so on, less volatility indexes), they have a delay, like anyone else. Some of them have less delay, so the price moves differently.

**Comment by duyorion** [comment]
If the delay is not very big, like 1 - 2 pips, it's fine. If it is 10 pips, it's rude. I used to be cheated by a binary broker even with popular forex pair like eur/usd. That's why I asked the question. Volatility index is something like their own backyard in which no one can compare.

Thank you @binary-ex-machina .

Have a nice day!

duyorion
