### ISSUE TITLE
help me.

### ISSUE THREAD

**Issue by nhatthaihoaithu** [binary-ex-machina/binary.com-bot#70]
hello sir.
i have a bot, but it can not work, i understand why?
please tell me why?
![Capture](https://user-images.githubusercontent.com/45219329/56707535-7a124c00-6743-11e9-9fd4-ecbccc402bea.PNG)
in this picture, blue pen is mean:
example: slots is 1910
digit 1: 1
digit 2: 9
digit 3: 1
digit 4: 0
if digit 1 + digit 2 =10, and digit 3 + digit 4<10, precition is : sum of digit 3+ digit 4
but my bot can not do it.
[MATCH(TAN-TEST LAN 1.zip](https://github.com/binary-ex-machina/binary.com-bot/files/3114938/MATCH.TAN-TEST.LAN.1.zip)

**Comment by binary-ex-machina** [comment]
When you analyse the tick as a letter, you can't use math operations with it, since they are strings and not numbers. On volatility Indexes 100, there is 2 decimals, so you need to consider the comma as a letter too. 

You need to transform them into numbers when making the operation. Another problem is that you placing this analysis on the Run Once At Start, so it will run only one time, and not after every trade. You need to keep the bot looping in the first block, until the condition is met, before it defines the prediction. When it finds the condition, it will break out the loop, define the prediction and buy the contract.

![image](https://user-images.githubusercontent.com/34610787/56871786-84a93b80-69f8-11e9-80ca-d4cce89243e1.png)
