### ISSUE TITLE
Bot wanted.

### ISSUE THREAD

**Issue by Tebu1429** [binary-ex-machina/binary.com-bot#82]
Hi .
Is there anyway ,you could share any bot which really works for you.

I am new on this .and I am loosing all my money with no profit at all.

Thank you!

**Comment by binary-ex-machina** [comment]
Learn how to read the market and try to find good entry points to play a simple Call/Put bot. In order to rely on a strategy that a bot will analyse, you need to have good balance and a lot of luck. It's impossible to make money by just playing the bot and wait for the money appear. No bot can analyse the market better the human eye, not for now.

**Comment by binary-ex-machina** [comment]
My strategy is very simple. On the chart, put a SMA with period 50. When the candle cross over, you play Call until win. If the candle crosses down the SMA, you play put until win. Make 3% a day and stop
